// Neo4j Cypher Import Statements for Smart Bharat AI
CREATE (:Module {id: '.agents/AGENTS.md', name: 'AGENTS', layer: 'root', type: 'document', size: 2089, complexity: 1});
CREATE (:Module {id: '.code-review-graph/.gitignore', name: '.gitignore', layer: 'root', type: 'module', size: 145, complexity: 1});
CREATE (:Module {id: '.code-review-graph/graph.db', name: 'graph', layer: 'root', type: 'module', size: 1081344, complexity: 1});
CREATE (:Module {id: '.code-review-graph/graph.db-shm', name: 'graph', layer: 'root', type: 'module', size: 32768, complexity: 1});
CREATE (:Module {id: '.code-review-graph/graph.db-wal', name: 'graph', layer: 'root', type: 'module', size: 0, complexity: 1});
CREATE (:Module {id: '.env', name: '.env', layer: 'root', type: 'module', size: 2042, complexity: 1});
CREATE (:Module {id: '.env.example', name: '.env', layer: 'root', type: 'module', size: 2406, complexity: 1});
CREATE (:Module {id: '.env.local', name: '.env', layer: 'root', type: 'module', size: 1787, complexity: 1});
CREATE (:Module {id: '.gitignore', name: '.gitignore', layer: 'root', type: 'module', size: 424, complexity: 1});
CREATE (:Module {id: 'AGENTS.md', name: 'AGENTS', layer: 'root', type: 'document', size: 44556, complexity: 1});
CREATE (:Module {id: 'backend/.env', name: '.env', layer: 'backend', type: 'module', size: 359, complexity: 1});
CREATE (:Module {id: 'backend/api/index.ts', name: 'index', layer: 'backend', type: 'module', size: 111, complexity: 1});
CREATE (:Module {id: 'backend/package-lock.json', name: 'package-lock', layer: 'backend', type: 'module', size: 69738, complexity: 1});
CREATE (:Module {id: 'backend/package.json', name: 'package', layer: 'backend', type: 'module', size: 839, complexity: 1});
CREATE (:Module {id: 'backend/src/app.ts', name: 'app', layer: 'backend', type: 'module', size: 3603, complexity: 12});
CREATE (:Module {id: 'backend/src/config/index.ts', name: 'index', layer: 'backend', type: 'config', size: 1410, complexity: 7});
CREATE (:Module {id: 'backend/src/controllers/auth.controller.ts', name: 'auth.controller', layer: 'backend', type: 'controller', size: 8455, complexity: 23});
CREATE (:Module {id: 'backend/src/database/db.ts', name: 'db', layer: 'backend', type: 'model', size: 7364, complexity: 26});
CREATE (:Module {id: 'backend/src/routes/auth.routes.ts', name: 'auth.routes', layer: 'backend', type: 'route', size: 1933, complexity: 3});
CREATE (:Module {id: 'backend/src/routes/complaints.routes.ts', name: 'complaints.routes', layer: 'backend', type: 'route', size: 2272, complexity: 8});
CREATE (:Module {id: 'backend/src/routes/govid.routes.ts', name: 'govid.routes', layer: 'backend', type: 'route', size: 1469, complexity: 2});
CREATE (:Module {id: 'backend/src/routes/index.ts', name: 'index', layer: 'backend', type: 'route', size: 571, complexity: 1});
CREATE (:Module {id: 'backend/src/routes/schemes.routes.ts', name: 'schemes.routes', layer: 'backend', type: 'route', size: 2647, complexity: 8});
CREATE (:Module {id: 'backend/src/server.ts', name: 'server', layer: 'backend', type: 'module', size: 567, complexity: 1});
CREATE (:Module {id: 'backend/src/services/auth.service.ts', name: 'auth.service', layer: 'backend', type: 'service', size: 13864, complexity: 45});
CREATE (:Module {id: 'backend/src/utils/hash.util.ts', name: 'hash.util', layer: 'backend', type: 'util', size: 1020, complexity: 2});
CREATE (:Module {id: 'backend/src/utils/jwt.util.ts', name: 'jwt.util', layer: 'backend', type: 'util', size: 1328, complexity: 2});
CREATE (:Module {id: 'backend/src/utils/otp.util.ts', name: 'otp.util', layer: 'backend', type: 'util', size: 113, complexity: 1});
CREATE (:Module {id: 'backend/tsconfig.json', name: 'tsconfig', layer: 'backend', type: 'module', size: 373, complexity: 1});
CREATE (:Module {id: 'backend/vercel.json', name: 'vercel', layer: 'backend', type: 'module', size: 378, complexity: 1});
CREATE (:Module {id: 'data/smart_bharat_db.json', name: 'smart_bharat_db', layer: 'data', type: 'module', size: 4210, complexity: 1});
CREATE (:Module {id: 'DESIGN.md', name: 'DESIGN', layer: 'root', type: 'document', size: 1160, complexity: 1});
CREATE (:Module {id: 'docs/firebase-auth.md', name: 'firebase-auth', layer: 'docs', type: 'document', size: 4007, complexity: 1});
CREATE (:Module {id: 'e2e/button_audit.spec.ts', name: 'button_audit.spec', layer: 'e2e', type: 'module', size: 1994, complexity: 13});
CREATE (:Module {id: 'frontend/.env', name: '.env', layer: 'frontend', type: 'module', size: 1923, complexity: 1});
CREATE (:Module {id: 'frontend/.env.local', name: '.env', layer: 'frontend', type: 'module', size: 1936, complexity: 1});
CREATE (:Module {id: 'frontend/components.json', name: 'components', layer: 'frontend', type: 'module', size: 520, complexity: 1});
CREATE (:Module {id: 'frontend/eslint.config.mjs', name: 'eslint.config', layer: 'frontend', type: 'module', size: 465, complexity: 1});
CREATE (:Module {id: 'frontend/next-env.d.ts', name: 'next-env.d', layer: 'frontend', type: 'module', size: 211, complexity: 2});
CREATE (:Module {id: 'frontend/next.config.ts', name: 'next.config', layer: 'frontend', type: 'module', size: 2420, complexity: 3});
CREATE (:Module {id: 'frontend/package-lock.json', name: 'package-lock', layer: 'frontend', type: 'module', size: 290795, complexity: 1});
CREATE (:Module {id: 'frontend/package.json', name: 'package', layer: 'frontend', type: 'module', size: 1033, complexity: 1});
CREATE (:Module {id: 'frontend/postcss.config.mjs', name: 'postcss.config', layer: 'frontend', type: 'module', size: 94, complexity: 1});
CREATE (:Module {id: 'frontend/src/app/admin/ids/page.tsx', name: 'page', layer: 'frontend', type: 'page', size: 9717, complexity: 5});
CREATE (:Module {id: 'frontend/src/app/admin/page.tsx', name: 'page', layer: 'frontend', type: 'page', size: 11427, complexity: 6});
CREATE (:Module {id: 'frontend/src/app/ai/page.tsx', name: 'page', layer: 'frontend', type: 'page', size: 116, complexity: 1});
CREATE (:Module {id: 'frontend/src/app/api/assistant/route.ts', name: 'route', layer: 'frontend', type: 'module', size: 1023, complexity: 4});
CREATE (:Module {id: 'frontend/src/app/assistant/page.tsx', name: 'page', layer: 'frontend', type: 'page', size: 26045, complexity: 30});
CREATE (:Module {id: 'frontend/src/app/complaints/page.tsx', name: 'page', layer: 'frontend', type: 'page', size: 29653, complexity: 10});
CREATE (:Module {id: 'frontend/src/app/credentials/page.tsx', name: 'page', layer: 'frontend', type: 'page', size: 20934, complexity: 31});
CREATE (:Module {id: 'frontend/src/app/forgot-password/page.tsx', name: 'page', layer: 'frontend', type: 'page', size: 7321, complexity: 6});
CREATE (:Module {id: 'frontend/src/app/framework/page.tsx', name: 'page', layer: 'frontend', type: 'page', size: 614, complexity: 2});
CREATE (:Module {id: 'frontend/src/app/globals.css', name: 'globals', layer: 'frontend', type: 'style', size: 7761, complexity: 1});
CREATE (:Module {id: 'frontend/src/app/id/page.tsx', name: 'page', layer: 'frontend', type: 'page', size: 16340, complexity: 19});
CREATE (:Module {id: 'frontend/src/app/id/track/page.tsx', name: 'page', layer: 'frontend', type: 'page', size: 7591, complexity: 12});
CREATE (:Module {id: 'frontend/src/app/id/[id]/page.tsx', name: 'page', layer: 'frontend', type: 'page', size: 14737, complexity: 10});
CREATE (:Module {id: 'frontend/src/app/layout.tsx', name: 'layout', layer: 'frontend', type: 'page', size: 3058, complexity: 3});
CREATE (:Module {id: 'frontend/src/app/login/page.tsx', name: 'page', layer: 'frontend', type: 'page', size: 22222, complexity: 25});
CREATE (:Module {id: 'frontend/src/app/manifest.ts', name: 'manifest', layer: 'frontend', type: 'module', size: 508, complexity: 1});
CREATE (:Module {id: 'frontend/src/app/page.tsx', name: 'page', layer: 'frontend', type: 'page', size: 97, complexity: 1});
CREATE (:Module {id: 'frontend/src/app/privacy/page.tsx', name: 'page', layer: 'frontend', type: 'page', size: 593, complexity: 2});
CREATE (:Module {id: 'frontend/src/app/profile/page.tsx', name: 'page', layer: 'frontend', type: 'page', size: 4095, complexity: 10});
CREATE (:Module {id: 'frontend/src/app/reset-password/page.tsx', name: 'page', layer: 'frontend', type: 'page', size: 8190, complexity: 9});
CREATE (:Module {id: 'frontend/src/app/robots.ts', name: 'robots', layer: 'frontend', type: 'module', size: 371, complexity: 1});
CREATE (:Module {id: 'frontend/src/app/schemes/page.tsx', name: 'page', layer: 'frontend', type: 'page', size: 25854, complexity: 34});
CREATE (:Module {id: 'frontend/src/app/schemes/track/page.tsx', name: 'page', layer: 'frontend', type: 'page', size: 3780, complexity: 10});
CREATE (:Module {id: 'frontend/src/app/schemes/[id]/page.tsx', name: 'page', layer: 'frontend', type: 'page', size: 516, complexity: 2});
CREATE (:Module {id: 'frontend/src/app/schemes/[id]/SchemeDetailsClient.tsx', name: 'SchemeDetailsClient', layer: 'frontend', type: 'module', size: 5830, complexity: 2});
CREATE (:Module {id: 'frontend/src/app/security/page.tsx', name: 'page', layer: 'frontend', type: 'page', size: 589, complexity: 2});
CREATE (:Module {id: 'frontend/src/app/signup/page.tsx', name: 'page', layer: 'frontend', type: 'page', size: 15257, complexity: 17});
CREATE (:Module {id: 'frontend/src/app/sitemap.ts', name: 'sitemap', layer: 'frontend', type: 'module', size: 1261, complexity: 2});
CREATE (:Module {id: 'frontend/src/app/standards/page.tsx', name: 'page', layer: 'frontend', type: 'page', size: 606, complexity: 2});
CREATE (:Module {id: 'frontend/src/app/terms/page.tsx', name: 'page', layer: 'frontend', type: 'page', size: 595, complexity: 2});
CREATE (:Module {id: 'frontend/src/app/track/page.tsx', name: 'page', layer: 'frontend', type: 'page', size: 10276, complexity: 9});
CREATE (:Module {id: 'frontend/src/app/vault/page.tsx', name: 'page', layer: 'frontend', type: 'page', size: 121, complexity: 1});
CREATE (:Module {id: 'frontend/src/components/ai/AIAssistant.tsx', name: 'AIAssistant', layer: 'frontend', type: 'component', size: 8890, complexity: 25});
CREATE (:Module {id: 'frontend/src/components/ai/AssistantThreeScene.tsx', name: 'AssistantThreeScene', layer: 'frontend', type: 'component', size: 4400, complexity: 6});
CREATE (:Module {id: 'frontend/src/components/AppPreloader.tsx', name: 'AppPreloader', layer: 'frontend', type: 'component', size: 985, complexity: 4});
CREATE (:Module {id: 'frontend/src/components/auth/PasswordStrengthMeter.tsx', name: 'PasswordStrengthMeter', layer: 'frontend', type: 'component', size: 2803, complexity: 12});
CREATE (:Module {id: 'frontend/src/components/ClientShells.tsx', name: 'ClientShells', layer: 'frontend', type: 'component', size: 446, complexity: 2});
CREATE (:Module {id: 'frontend/src/components/ComplaintsShowcase.tsx', name: 'ComplaintsShowcase', layer: 'frontend', type: 'component', size: 4136, complexity: 4});
CREATE (:Module {id: 'frontend/src/components/DocumentSelector.tsx', name: 'DocumentSelector', layer: 'frontend', type: 'component', size: 16838, complexity: 54});
CREATE (:Module {id: 'frontend/src/components/DynamicForm.tsx', name: 'DynamicForm', layer: 'frontend', type: 'component', size: 19044, complexity: 47});
CREATE (:Module {id: 'frontend/src/components/EligibilityEngine.tsx', name: 'EligibilityEngine', layer: 'frontend', type: 'component', size: 10856, complexity: 14});
CREATE (:Module {id: 'frontend/src/components/Footer.tsx', name: 'Footer', layer: 'frontend', type: 'component', size: 2178, complexity: 2});
CREATE (:Module {id: 'frontend/src/components/Hero.tsx', name: 'Hero', layer: 'frontend', type: 'component', size: 11864, complexity: 6});
CREATE (:Module {id: 'frontend/src/components/HeroShowcase.tsx', name: 'HeroShowcase', layer: 'frontend', type: 'component', size: 1671, complexity: 6});
CREATE (:Module {id: 'frontend/src/components/Navbar.tsx', name: 'Navbar', layer: 'frontend', type: 'component', size: 13991, complexity: 30});
CREATE (:Module {id: 'frontend/src/components/PageWrapper.tsx', name: 'PageWrapper', layer: 'frontend', type: 'component', size: 610, complexity: 2});
CREATE (:Module {id: 'frontend/src/components/RouteGuard.tsx', name: 'RouteGuard', layer: 'frontend', type: 'component', size: 1590, complexity: 6});
CREATE (:Module {id: 'frontend/src/components/SmartUpload.tsx', name: 'SmartUpload', layer: 'frontend', type: 'component', size: 5771, complexity: 21});
CREATE (:Module {id: 'frontend/src/components/SpotlightCard.css', name: 'SpotlightCard', layer: 'frontend', type: 'component', size: 602, complexity: 1});
CREATE (:Module {id: 'frontend/src/components/SpotlightCard.tsx', name: 'SpotlightCard', layer: 'frontend', type: 'component', size: 991, complexity: 4});
CREATE (:Module {id: 'frontend/src/components/ui/card.tsx', name: 'card', layer: 'frontend', type: 'component', size: 1793, complexity: 1});
CREATE (:Module {id: 'frontend/src/components/ui/interactive-3d-robot.tsx', name: 'interactive-3d-robot', layer: 'frontend', type: 'component', size: 3854, complexity: 5});
CREATE (:Module {id: 'frontend/src/context/AuthContext.tsx', name: 'AuthContext', layer: 'frontend', type: 'context', size: 10507, complexity: 50});
CREATE (:Module {id: 'frontend/src/lib/ai/orchestrator.ts', name: 'orchestrator', layer: 'frontend', type: 'util', size: 8212, complexity: 40});
CREATE (:Module {id: 'frontend/src/lib/ai/rag.ts', name: 'rag', layer: 'frontend', type: 'util', size: 4609, complexity: 23});
CREATE (:Module {id: 'frontend/src/lib/ai/types.ts', name: 'types', layer: 'frontend', type: 'type', size: 1643, complexity: 14});
CREATE (:Module {id: 'frontend/src/lib/api/auth.api.ts', name: 'auth.api', layer: 'frontend', type: 'util', size: 1582, complexity: 3});
CREATE (:Module {id: 'frontend/src/lib/api/client.ts', name: 'client', layer: 'frontend', type: 'util', size: 794, complexity: 5});
CREATE (:Module {id: 'frontend/src/lib/auth.ts', name: 'auth', layer: 'frontend', type: 'util', size: 9516, complexity: 62});
CREATE (:Module {id: 'frontend/src/lib/data.ts', name: 'data', layer: 'frontend', type: 'util', size: 71596, complexity: 187});
CREATE (:Module {id: 'frontend/src/lib/firebase.ts', name: 'firebase', layer: 'frontend', type: 'util', size: 1366, complexity: 6});
CREATE (:Module {id: 'frontend/src/lib/knowledge.ts', name: 'knowledge', layer: 'frontend', type: 'util', size: 17963, complexity: 49});
CREATE (:Module {id: 'frontend/src/lib/useChatHistory.ts', name: 'useChatHistory', layer: 'frontend', type: 'util', size: 5591, complexity: 33});
CREATE (:Module {id: 'frontend/src/lib/utils.ts', name: 'utils', layer: 'frontend', type: 'util', size: 1472, complexity: 18});
CREATE (:Module {id: 'frontend/tsconfig.json', name: 'tsconfig', layer: 'frontend', type: 'module', size: 669, complexity: 1});
CREATE (:Module {id: 'frontend/tsconfig.tsbuildinfo', name: 'tsconfig', layer: 'frontend', type: 'module', size: 154844, complexity: 1});
CREATE (:Module {id: 'memory/api.md', name: 'api', layer: 'root', type: 'document', size: 430, complexity: 1});
CREATE (:Module {id: 'memory/architecture.md', name: 'architecture', layer: 'root', type: 'document', size: 7538, complexity: 1});
CREATE (:Module {id: 'memory/bugs.md', name: 'bugs', layer: 'root', type: 'document', size: 1543, complexity: 1});
CREATE (:Module {id: 'memory/business-rules.md', name: 'business-rules', layer: 'root', type: 'document', size: 2276, complexity: 1});
CREATE (:Module {id: 'memory/changelog.md', name: 'changelog', layer: 'root', type: 'document', size: 7177, complexity: 1});
CREATE (:Module {id: 'memory/coding-standards.md', name: 'coding-standards', layer: 'root', type: 'document', size: 597, complexity: 1});
CREATE (:Module {id: 'memory/current-status.md', name: 'current-status', layer: 'root', type: 'document', size: 3454, complexity: 1});
CREATE (:Module {id: 'memory/database.md', name: 'database', layer: 'root', type: 'document', size: 1069, complexity: 1});
CREATE (:Module {id: 'memory/decisions.md', name: 'decisions', layer: 'root', type: 'document', size: 511, complexity: 1});
CREATE (:Module {id: 'memory/deployment.md', name: 'deployment', layer: 'root', type: 'document', size: 574, complexity: 1});
CREATE (:Module {id: 'memory/how-to-run.md', name: 'how-to-run', layer: 'root', type: 'document', size: 287, complexity: 1});
CREATE (:Module {id: 'memory/module-government-ids.md', name: 'module-government-ids', layer: 'root', type: 'document', size: 5129, complexity: 1});
CREATE (:Module {id: 'memory/production-implementation-spec.md', name: 'production-implementation-spec', layer: 'root', type: 'document', size: 5956, complexity: 1});
CREATE (:Module {id: 'memory/project-overview.md', name: 'project-overview', layer: 'root', type: 'document', size: 1142, complexity: 1});
CREATE (:Module {id: 'memory/README.md', name: 'README', layer: 'root', type: 'document', size: 2414, complexity: 1});
CREATE (:Module {id: 'memory/tech-stack.md', name: 'tech-stack', layer: 'root', type: 'document', size: 732, complexity: 1});
CREATE (:Module {id: 'memory/todo.md', name: 'todo', layer: 'root', type: 'document', size: 1067, complexity: 1});
CREATE (:Module {id: 'package-lock.json', name: 'package-lock', layer: 'root', type: 'module', size: 316896, complexity: 1});
CREATE (:Module {id: 'package.json', name: 'package', layer: 'root', type: 'module', size: 785, complexity: 1});
CREATE (:Module {id: 'PRODUCT.md', name: 'PRODUCT', layer: 'root', type: 'document', size: 1099, complexity: 1});
CREATE (:Module {id: 'README.md', name: 'README', layer: 'root', type: 'document', size: 16070, complexity: 1});
CREATE (:Module {id: 'scripts/build-review-graph.js', name: 'build-review-graph', layer: 'root', type: 'script', size: 17578, complexity: 17});
CREATE (:Module {id: 'scripts/dev.js', name: 'dev', layer: 'root', type: 'script', size: 560, complexity: 1});
CREATE (:Module {id: 'scripts/graphify.js', name: 'graphify', layer: 'root', type: 'script', size: 14632, complexity: 84});
CREATE (:Module {id: 'scripts/validate-graph-output.js', name: 'validate-graph-output', layer: 'root', type: 'script', size: 4264, complexity: 8});
CREATE (:Module {id: 'shared/package.json', name: 'package', layer: 'shared', type: 'module', size: 225, complexity: 1});
CREATE (:Module {id: 'shared/src/index.ts', name: 'index', layer: 'shared', type: 'module', size: 70, complexity: 1});
CREATE (:Module {id: 'shared/src/types/auth.ts', name: 'auth', layer: 'shared', type: 'type', size: 1899, complexity: 16});
CREATE (:Module {id: 'shared/src/validations/password.ts', name: 'password', layer: 'shared', type: 'validation', size: 1048, complexity: 11});
CREATE (:Module {id: 'shared/tsconfig.json', name: 'tsconfig', layer: 'shared', type: 'module', size: 287, complexity: 1});
CREATE (:Module {id: 'testsprite_tests/standard_prd.json', name: 'standard_prd', layer: 'root', type: 'module', size: 2966, complexity: 1});
CREATE (:Module {id: 'testsprite_tests/TC-BE-001_Health_Check_API_Endpoint.py', name: 'TC-BE-001_Health_Check_API_Endpoint', layer: 'root', type: 'module', size: 2339, complexity: 1});
CREATE (:Module {id: 'testsprite_tests/TC-BE-002_User_Authentication__JWT_Profile_Verification.py', name: 'TC-BE-002_User_Authentication__JWT_Profile_Verification', layer: 'root', type: 'module', size: 3607, complexity: 1});
CREATE (:Module {id: 'testsprite_tests/TC-FE-001_Dashboard_Hero_Video__Header_Navigation.py', name: 'TC-FE-001_Dashboard_Hero_Video__Header_Navigation', layer: 'root', type: 'module', size: 2652, complexity: 1});
CREATE (:Module {id: 'testsprite_tests/TC-FE-002_Government_Schemes_Search__Category_Modal.py', name: 'TC-FE-002_Government_Schemes_Search__Category_Modal', layer: 'root', type: 'module', size: 2695, complexity: 1});
CREATE (:Module {id: 'testsprite_tests/TC-FE-003_Scheme_Detail_Page__Application_Process.py', name: 'TC-FE-003_Scheme_Detail_Page__Application_Process', layer: 'root', type: 'module', size: 5166, complexity: 1});
CREATE (:Module {id: 'testsprite_tests/TC-FE-004_Foundational_Government_IDs_Portal__Wizard.py', name: 'TC-FE-004_Foundational_Government_IDs_Portal__Wizard', layer: 'root', type: 'module', size: 5645, complexity: 1});
CREATE (:Module {id: 'testsprite_tests/TC-FE-005_Civic_Complaints_Showcase__Category_Grid.py', name: 'TC-FE-005_Civic_Complaints_Showcase__Category_Grid', layer: 'root', type: 'module', size: 4836, complexity: 1});
CREATE (:Module {id: 'testsprite_tests/TC-FE-006_247_AI_Policy_Assistant_Conversational_Interface.py', name: 'TC-FE-006_247_AI_Policy_Assistant_Conversational_Interface', layer: 'root', type: 'module', size: 4839, complexity: 1});
CREATE (:Module {id: 'testsprite_tests/TC-FE-007_User_Credential_Vault__Digital_Wallet.py', name: 'TC-FE-007_User_Credential_Vault__Digital_Wallet', layer: 'root', type: 'module', size: 3002, complexity: 1});
CREATE (:Module {id: 'testsprite_tests/TC-FE-008_Mobile_Responsiveness__Viewport_Scaling.py', name: 'TC-FE-008_Mobile_Responsiveness__Viewport_Scaling', layer: 'root', type: 'module', size: 4327, complexity: 1});
CREATE (:Module {id: 'testsprite_tests/TC-SEC-001_Input_Sanitization__Injection_Prevention.py', name: 'TC-SEC-001_Input_Sanitization__Injection_Prevention', layer: 'root', type: 'module', size: 4548, complexity: 1});
CREATE (:Module {id: 'testsprite_tests/testsprite_frontend_test_plan.json', name: 'testsprite_frontend_test_plan', layer: 'root', type: 'module', size: 6820, complexity: 1});
CREATE (:Module {id: 'testsprite_tests/tmp/code_summary.yaml', name: 'code_summary', layer: 'root', type: 'module', size: 3648, complexity: 1});
CREATE (:Module {id: 'testsprite_tests/tmp/config.json', name: 'config', layer: 'root', type: 'module', size: 697, complexity: 1});
CREATE (:Module {id: 'testsprite_tests/tmp/prd_files/README.md', name: 'README', layer: 'root', type: 'document', size: 1450, complexity: 1});
CREATE (:Module {id: 'testsprite_tests/tmp/raw_report.md', name: 'raw_report', layer: 'root', type: 'document', size: 11277, complexity: 1});
CREATE (:Module {id: 'testsprite_tests/tmp/test_results.json', name: 'test_results', layer: 'root', type: 'module', size: 59261, complexity: 1});
CREATE (:Module {id: 'vercel.json', name: 'vercel', layer: 'root', type: 'module', size: 346, complexity: 1});
MATCH (s:Module {id: 'backend/api/index.ts'}), (t:Module {id: 'backend/src/app.ts'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'backend/src/app.ts'}), (t:Module {id: 'backend/src/routes/index.ts'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'backend/src/app.ts'}), (t:Module {id: 'backend/src/config/index.ts'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'backend/src/controllers/auth.controller.ts'}), (t:Module {id: 'backend/src/services/auth.service.ts'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'backend/src/controllers/auth.controller.ts'}), (t:Module {id: 'backend/src/database/db.ts'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'backend/src/controllers/auth.controller.ts'}), (t:Module {id: 'backend/src/utils/jwt.util.ts'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'backend/src/database/db.ts'}), (t:Module {id: 'shared/src/index.ts'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'backend/src/routes/auth.routes.ts'}), (t:Module {id: 'backend/src/controllers/auth.controller.ts'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'backend/src/routes/index.ts'}), (t:Module {id: 'backend/src/routes/auth.routes.ts'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'backend/src/routes/index.ts'}), (t:Module {id: 'backend/src/routes/govid.routes.ts'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'backend/src/routes/index.ts'}), (t:Module {id: 'backend/src/routes/schemes.routes.ts'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'backend/src/routes/index.ts'}), (t:Module {id: 'backend/src/routes/complaints.routes.ts'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'backend/src/server.ts'}), (t:Module {id: 'backend/src/app.ts'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'backend/src/server.ts'}), (t:Module {id: 'backend/src/config/index.ts'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'backend/src/server.ts'}), (t:Module {id: 'backend/src/database/db.ts'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'backend/src/services/auth.service.ts'}), (t:Module {id: 'backend/src/database/db.ts'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'backend/src/services/auth.service.ts'}), (t:Module {id: 'backend/src/utils/hash.util.ts'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'backend/src/services/auth.service.ts'}), (t:Module {id: 'backend/src/utils/otp.util.ts'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'backend/src/services/auth.service.ts'}), (t:Module {id: 'shared/src/index.ts'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'backend/src/services/auth.service.ts'}), (t:Module {id: 'backend/src/config/index.ts'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'backend/src/services/auth.service.ts'}), (t:Module {id: 'backend/src/utils/jwt.util.ts'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'backend/src/utils/jwt.util.ts'}), (t:Module {id: 'backend/src/config/index.ts'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'frontend/src/app/layout.tsx'}), (t:Module {id: 'frontend/src/app/globals.css'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'frontend/src/app/schemes/[id]/page.tsx'}), (t:Module {id: 'frontend/src/app/schemes/[id]/SchemeDetailsClient.tsx'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'frontend/src/components/auth/PasswordStrengthMeter.tsx'}), (t:Module {id: 'shared/src/index.ts'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'frontend/src/components/DynamicForm.tsx'}), (t:Module {id: 'frontend/src/components/SmartUpload.tsx'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'frontend/src/components/SmartUpload.tsx'}), (t:Module {id: 'frontend/src/components/DocumentSelector.tsx'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'frontend/src/components/SpotlightCard.tsx'}), (t:Module {id: 'frontend/src/components/SpotlightCard.css'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'frontend/src/lib/ai/orchestrator.ts'}), (t:Module {id: 'frontend/src/lib/ai/rag.ts'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'frontend/src/lib/ai/orchestrator.ts'}), (t:Module {id: 'frontend/src/lib/ai/types.ts'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'frontend/src/lib/ai/rag.ts'}), (t:Module {id: 'frontend/src/lib/ai/types.ts'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'frontend/src/lib/api/auth.api.ts'}), (t:Module {id: 'frontend/src/lib/api/client.ts'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
MATCH (s:Module {id: 'frontend/src/lib/auth.ts'}), (t:Module {id: 'frontend/src/lib/firebase.ts'}) CREATE (s)-[:IMPORTS {weight: 1}]->(t);
